version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "root"
    ports:
      - "9091:9090"  
    volumes:
      - /opt/prometheus:/prometheus:rw
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.retention.time=6h'
    networks:
      - aruba_default

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.32.2
    container_name: thanos-sidecar
    user: "root"
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --prometheus.url=http://prometheus:9090
      - --objstore.config-file=/etc/thanos/objstore.yml
    volumes:
      - /opt/prometheus:/prometheus:rw
      - ./thanos-config:/etc/thanos:rw
    networks:
      - aruba_default

  thanos-query:
    image: quay.io/thanos/thanos:v0.32.2
    container_name: thanos-query
    ports:
      - "10902:10902"
    command:
      - query
      - --http-address=0.0.0.0:10902
      - --store=thanos-sidecar:10901
      - --store=thanos-store:10901
    networks:
      - aruba_default

  thanos-store:
    image: quay.io/thanos/thanos:v0.32.2
    container_name: thanos-store
    user: "1000:1000"
    command:
      - store
      - --objstore.config-file=/etc/thanos/objstore.yml
      - --data-dir=/data
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
    volumes:
      - ./thanos-config:/etc/thanos:rw
      - ./data:/data:rw
    networks:
      - aruba_default

networks:
  aruba_default:
    external: true
